apiVersion: apps/v1
kind: Deployment
metadata:
  name: addtis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: addtis
  template:
    metadata:
      labels:
        app: addtis
    spec:
      containers:
      - image: okteto.dev/addtis:latest
        name: addtis
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "af035530-b0b4-47eb-baae-be5a7d713ba7"
        - name: Vless_Path
          value: "/vfdxd555"
        - name: Vmess_UUID
          value: "af035530-b0b4-47eb-baae-be5a7d713ba7"
        - name: Vmess_Path
          value: "/vfdxd555"
        - name: Share_Path
          value: "/v2link"
